### Llamada con la API todos los usuarios
GET http://localhost:3000/api/user

### Llamada con la API un solo usuario 
GET http://localhost:3000/api/user/3

### POST
POST http://localhost:3000/api/user HTTP/1.1
Content-Type: application/json

{
    "name": "Juan" ,
    "lastName": "Pedro pepe",
    "email": "batmaaaan@test.com"
}

### Modificar un User (PUT --> con todas las entidades, PATCH --> modifica alguna de las entidades, no todas)
PUT http://localhost:3000/api/user/3 HTTP/1.1
Content-Type: application/json

{   
    "name": "TenerCuidado" ,
    "lastName": "Con Patch",
    "rol":  ["Tester","Programador","DBA","PM"],
    "email": "PATCHdejanull@test.com"
}

### Modificaciones parciales
PATCH  http://localhost:3000/api/user/3 HTTP/1.1
Content-Type: application/json

{   
    "rol":  ["Tester","PM"]
}

### Borrar un User
DELETE http://localhost:3000/api/user/4