### Llamada con la API todos los usuarios
get http://localhost:3000/api/users

### Llamada con la API un solo usuario 
get http://localhost:3000/api/user/000123

### Crear un nuevo User
POST http://localhost:3000/api/user 
Content-Type: application/json

{
    "name": "Batman" ,
    "lastName": "Bat",
    "rol": ["DBA"],
    "email": "batman@test.com",
    "id":"000124"
}

### Modificar un User (PUT --> con todas las entidades, PATCH --> modifica alguna de las entidades, no todas)
PUT http://localhost:3000/api/user/000123 HTTP/1.1
Content-Type: application/json

{
    "name": "Batman" ,
    "lastName": "Modif 2",
    "rol":  ["Programador", "PM", "Tester"],
    "email": "pepe_grillo_bat@test.com",
    "id":"000123"
}

