### GET
GET http://localhost:3000/api/project

### POST
# @name project
POST http://localhost:3000/api/project HTTP/1.1
Content-Type: application/json

{
"projectDescription":"Odiseo"
}

### GET ONE
@id = {{project.response.body.data.projectId}}
GET http://localhost:3000/api/project/{{id}}

### PUT
PUT http://localhost:3000/api/project/{{id}} HTTP/1.1
Content-Type: application/json

{   
"projectDescription": "Cambio nombre"
}

### DELETE
DELETE http://localhost:3000/api/project/{{id}}